{
 "title": "Gloo Gateway Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Made",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (envoy_http_rq_total{envoy_http_conn_manager_prefix!=\"prometheus\"})",
     "legendFormat": "{{testid}} - "
    }
   ]
  },
  {
   "title": "K6 runners",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{run_id=\"$run_id\"}[5m])) by (status, version) >0",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Checks",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "k6_checks_rate{run_id=\"$run_id\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"gloo-system|keycloak|httpbin\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"gloo-system|keycloak|httpbin\", workload_type=\"deployment\"}\n) by (workload)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=~\"gloo-system|keycloak|httpbin\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"gloo-system|keycloak|httpbin\", workload_type=~\"deployment|job\"}\n) by (workload)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Envoy upstream request rate by Envoy cluster (w/o stats)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total[5m])) by (envoy_cluster_name)",
     "legendFormat": "{{ envoy_cluster_name }} {{ envoy_response_code }}"
    }
   ]
  },
  {
   "title": "HTTP request rate by Gateways (w/o stats)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_rq_total{envoy_http_conn_manager_prefix!~\"prometheus\"}[5m])) by (envoy_http_conn_manager_prefix)",
     "legendFormat": "{{envoy_http_conn_manager_prefix}}"
    }
   ]
  },
  {
   "title": "Envoy upstream request latency by Envoy cluster (w/o stats)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket[5m])) by (le, envoy_cluster_name))",
     "legendFormat": "p99 - {{envoy_cluster_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket[5m])) by (le, envoy_cluster_name))",
     "legendFormat": "p95 - {{envoy_cluster_name}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_upstream_rq_time_bucket[5m])) by (le, envoy_cluster_name))",
     "legendFormat": "p90 - {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "ExtAuthZ denied and RateLimit failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_ext_authz_denied_total[5m])",
     "legendFormat": "ExtAuthZ"
    },
    {
     "expr": "rate(envoy_cluster_ratelimit_failure_mode_allowed_total[5m])",
     "legendFormat": "RateLimit"
    }
   ]
  }
 ]
}