// Code generated by Autopilot. DO NOT EDIT.

// Package v1 contains API Schema definitions for the examples.io v1 API group
// +k8s:deepcopy-gen=package,register
// +groupName=examples.io
package v1
