// Code generated by Autopilot. DO NOT EDIT.

package v1

type AutoRoutePhase string

const (

	// AutoRoute is pending processing
	AutoRoutePhaseInitializing AutoRoutePhase = "Initializing"

	// AutoRoute is syncing with deployments in the cluster
	AutoRoutePhaseSyncing AutoRoutePhase = "Syncing"

	// AutoRoute is in-sync and ready to serve traffic
	AutoRoutePhaseReady AutoRoutePhase = "Ready"
)
