// Code generated by Autopilot. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// AutoRoute is the Schema for the autoRoute API
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=autoRoute,scope=Namespaced
type AutoRoute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AutoRouteSpec   `json:"spec,omitempty"`
	Status AutoRouteStatus `json:"status,omitempty"`
}

// AutoRouteStatus defines an observed condition of AutoRoute
// +k8s:openapi-gen=true
type AutoRouteStatus struct {
	// Phase represents the current state of the AutoRoute.
	Phase AutoRoutePhase `json:"phase,omitempty"`

	// ObservedGeneration was the last metadata.generation of the AutoRoute
	// observed by the operator. If this does not match the metadata.generation of the AutoRoute,
	// it means the operator has not yet reconciled the current generation of the operator
	ObservedGeneration int64 `json:"observedGeneration",omitempty`

	// StatusInfo defines the observed state of the AutoRoute in the cluster
	AutoRouteStatusInfo
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// AutoRouteList contains a list of AutoRoute
type AutoRouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AutoRoute `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AutoRoute{}, &AutoRouteList{})
}
