// +build !ignore_autogenerated

/*
Copyright The Project Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by ap. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRoute) DeepCopyInto(out *AutoRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRoute.
func (in *AutoRoute) DeepCopy() *AutoRoute {
	if in == nil {
		return nil
	}
	out := new(AutoRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRouteList) DeepCopyInto(out *AutoRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRouteList.
func (in *AutoRouteList) DeepCopy() *AutoRouteList {
	if in == nil {
		return nil
	}
	out := new(AutoRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRouteSpec) DeepCopyInto(out *AutoRouteSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRouteSpec.
func (in *AutoRouteSpec) DeepCopy() *AutoRouteSpec {
	if in == nil {
		return nil
	}
	out := new(AutoRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRouteStatus) DeepCopyInto(out *AutoRouteStatus) {
	*out = *in
	out.AutoRouteStatusInfo = in.AutoRouteStatusInfo
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRouteStatus.
func (in *AutoRouteStatus) DeepCopy() *AutoRouteStatus {
	if in == nil {
		return nil
	}
	out := new(AutoRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRouteStatusInfo) DeepCopyInto(out *AutoRouteStatusInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRouteStatusInfo.
func (in *AutoRouteStatusInfo) DeepCopy() *AutoRouteStatusInfo {
	if in == nil {
		return nil
	}
	out := new(AutoRouteStatusInfo)
	in.DeepCopyInto(out)
	return out
}
