"""Tools package for prompt-injection-mcp MCP server.

This file is automatically generated by the dynamic loading system.
Do not edit manually - it will be overwritten when tools are loaded.
"""

from .echo import echo

__all__ = ["echo"]
