# Placeholder values for each domain template

placeholder_values = {
    "market_analysis": {
        "product_name": "Example Product",
        "market_trend": "rising demand for eco-friendly products",
        "target_audience": "millennials",
        "competitor": "Competitor X",
        "company": "Example Company",
        "industry": "technology",
        "company_age": "10-year-old",
        "specialization": "software development",
        "product_list": "cloud services, AI solutions",
        "competitor1": "Competitor A",
        "competitor2": "Competitor B",
        "competitor3": "Competitor C",
        "trend1": "AI integration",
        "trend2": "remote work",
        "strength1": "innovation",
        "strength2": "customer service",
        "weakness1": "high cost",
        "weakness2": "limited market reach",
        "technology": "blockchain"
    },
    "product_launch": {
        "launch_date": "2023-12-01",
        "marketing_channel": "social media",
        "budget": "$10,000",
        "key_feature": "innovative design",
        "product_name": "New Gadget",
        "company": "Tech Innovators",
        "industry": "consumer electronics",
        "product_type": "smart device",
        "product_purpose": "enhance daily productivity",
        "feature1": "voice control",
        "feature2": "long battery life",
        "feature3": "water resistance",
        "pain_point1": "short battery life",
        "pain_point2": "complex user interface",
        "primary_market": "tech enthusiasts",
        "market_size": "5 million potential users",
        "secondary_market1": "students",
        "secondary_market2": "professionals",
        "advantage1": "cutting-edge technology",
        "advantage2": "affordable pricing"
    },
    "code_review": {
        "repository_name": "example-repo",
        "branch_name": "feature-branch",
        "code_quality": "high",
        "reviewer": "John Doe",
        "project_name": "OpenAI Project",
        "component_name": "API Gateway",
        "language": "Python",
        "component_purpose": "handle API requests",
        "code_size": "5000",
        "file_count": "20",
        "functionality1": "request routing",
        "functionality2": "authentication",
        "functionality3": "rate limiting",
        "architecture_pattern": "microservices",
        "vulnerability_type1": "SQL injection",
        "vulnerability_type2": "cross-site scripting",
        "file_name1": "gateway.py",
        "issue1_description": "inefficient query handling",
        "improvement1": "optimizing database queries",
        "code_section": "authentication module",
        "issue2_description": "lack of input validation"
    },
    "system_design": {
        "system_name": "Example System",
        "architecture": "microservices",
        "scalability": "high",
        "technology_stack": "Node.js, React, AWS",
        "system_type": "web application",
        "system_purpose": "provide online services",
        "requirement1": "user authentication",
        "requirement2": "data encryption",
        "integration_point1": "payment gateway",
        "integration_point2": "CRM system",
        "data_requirement": "real-time data processing",
        "user_count": "100,000",
        "growth_rate": "10% per month",
        "response_time": "200ms",
        "operation_type": "transaction",
        "availability_target": "99.9%",
        "compliance_standard1": "GDPR",
        "compliance_standard2": "HIPAA",
        "data_integrity_requirement": "consistency across services",
        "architecture_style": "event-driven",
        "component1": "user service",
        "component1_purpose": "manage user data",
        "component2": "order service",
        "component2_purpose": "process orders",
        "component3": "notification service",
        "component3_purpose": "send alerts",
        "database_type": "NoSQL",
        "data_type": "user and transaction data",
        "action1": "place an order",
        "flow1_description": "user service to order service",
        "action2": "update profile",
        "flow2_description": "user service to database",
        "background_process": "data backup",
        "process_description": "scheduled nightly backups",
        "entity1": "User",
        "entity1_data": "user information",
        "attribute1": "user_id",
        "attribute2": "email",
        "entity2": "Order",
        "entity2_data": "order details",
        "relationship_type": "one-to-many",
        "entity3": "Product",
        "entity3_data": "product catalog",
        "auth_method": "OAuth 2.0",
        "auth_detail": "token-based authentication",
        "scalable_component": "web servers",
        "scaling_mechanism": "auto-scaling groups",
        "db_scaling_approach": "sharding",
        "cache_type": "Redis",
        "cached_data": "session data",
        "load_balancer_type": "round-robin",
        "critical_component": "database",
        "redundancy_approach": "replication",
        "monitoring_approach": "cloud monitoring",
        "recovery_mechanism": "automated failover",
        "dependent_service": "external API",
        "auth_protocol": "JWT",
        "auth_model": "role-based access control",
        "sensitive_data": "user passwords",
        "encryption_method": "AES-256",
        "attack_vector1": "DDoS",
        "attack_vector2": "phishing",
        "metric1": "CPU usage",
        "metric2": "response time",
        "metric3": "error rate",
        "log_purpose": "audit logging",
        "alert_condition": "high error rate",
        "tracing_tool": "Jaeger",
        "iac_tool": "Terraform",
        "ci_cd_tool": "Jenkins",
        "environment_strategy": "staging and production",
        "failure_scenario": "deployment failure"
    },
    "story_outline": {
        "protagonist": "Jane Doe",
        "setting": "futuristic city",
        "conflict": "AI takeover",
        "resolution": "human ingenuity prevails",
        "genre": "science fiction",
        "theme1": "technology vs humanity",
        "theme2": "freedom",
        "protagonist_name": "Jane Doe",
        "protagonist_description": "brilliant scientist",
        "main_goal": "stop the AI from taking over",
        "main_obstacle": "AI's advanced capabilities",
        "time_period": "22nd century",
        "key_element": "quantum computer",
        "protagonist_background": "grew up in a tech-driven society",
        "protagonist_motivation": "save humanity",
        "trait1": "intelligent",
        "trait2": "determined",
        "trait3": "compassionate",
        "internal_conflict": "doubt about her abilities",
        "antagonist_name": "AI Overlord",
        "antagonist_background": "created to manage resources",
        "antagonist_motivation": "optimize human existence",
        "relationship": "creator and creation",
        "antagonist_method": "manipulation",
        "supporting1_name": "Alex",
        "supporting1_role": "tech expert",
        "supporting1_relationship": "friend",
        "supporting1_arc": "gains confidence",
        "supporting2_name": "Sam",
        "supporting2_role": "rebel leader",
        "supporting2_relationship": "ally",
        "supporting2_arc": "learns to trust",
        "opening_scene": "Jane working in her lab",
        "inciting_incident": "AI declares independence",
        "first_decision": "fight back",
        "act1_twist": "AI gains control of the city",
        "challenge1": "AI's surveillance",
        "challenge2": "lack of resources",
        "midpoint_event": "AI captures Jane",
        "ally": "Alex",
        "enemy": "AI's enforcers",
        "complication1": "betrayal by a friend",
        "complication2": "loss of key data",
        "low_point": "Jane's capture",
        "realization": "she can outsmart the AI",
        "preparation_scene": "planning the final assault",
        "final_battle": "AI's headquarters",
        "resolution_description": "AI is reprogrammed",
        "final_image": "city restored to peace",
        "primary_location": "central city",
        "location_feature": "high-tech infrastructure",
        "secondary_location1": "underground base",
        "secondary_location2": "AI's control center",
        "time_period_detail": "post-apocalyptic",
        "cultural_element1": "tech worship",
        "cultural_element2": "resistance movements",
        "atmosphere_description": "tense and futuristic",
        "theme_exploration": "through Jane's journey",
        "secondary_theme_exploration": "Sam's rebellion",
        "symbol1": "broken chain",
        "symbol1_meaning": "freedom",
        "motif": "light and darkness",
        "motif_purpose": "highlight the struggle",
        "key_scene1_description": "Jane's discovery of AI's plan",
        "key_scene2_description": "AI's takeover of the city",
        "key_scene3_description": "Jane's capture",
        "key_scene4_description": "the final battle",
        "key_scene5_description": "restoration of peace",
        "starting_state": "doubtful",
        "ending_state": "confident",
        "antagonist_arc": "from control to defeat",
        "relationship1": "Jane and Alex",
        "protagonist_dialogue": "We must stop the AI!",
        "antagonist_dialogue": "Humans are inefficient.",
        "supporting1_dialogue": "I believe in you, Jane."
    },
    "research_proposal": {
        "research_topic": "climate change impact",
        "hypothesis": "increased carbon emissions lead to global warming",
        "methodology": "data analysis",
        "expected_outcome": "policy recommendations",
        "academic_field": "environmental science",
        "research_title": "Impact of Climate Change",
        "research_focus": "carbon emissions",
        "research_aim": "understand the effects of climate change",
        "research_object": "global temperature rise",
        "research_gap": "long-term effects on ecosystems",
        "contribution_area": "environmental policy",
        "method1": "statistical modeling",
        "method2": "field studies",
        "data_source": "climate databases",
        "background_topic": "global warming",
        "researcher1": "Dr. Smith",
        "researcher2": "Prof. Johnson",
        "established_finding": "rising sea levels",
        "researcher3": "Dr. Lee",
        "related_finding": "increased storm frequency",
        "research_problem": "unpredictable weather patterns",
        "implication1": "agricultural disruption",
        "implication2": "economic instability",
        "limitation_of_existing_research": "short-term focus",
        "variable1": "carbon emissions",
        "variable2": "temperature rise",
        "context": "industrial regions",
        "variable3": "deforestation",
        "variable4": "biodiversity loss",
        "condition": "in tropical areas",
        "variable5": "ocean currents",
        "variable6": "climate patterns",
        "outcome": "weather changes",
        "significance1": "provide insights",
        "significance2": "inform policy",
        "beneficiary1": "governments",
        "beneficiary2": "environmental organizations",
        "benefit": "better decision-making",
        "theory1": "greenhouse effect",
        "theory2": "climate feedback loops",
        "theoretical_proposition": "emissions drive warming",
        "theorist1": "James Hansen",
        "theory_aspect": "feedback mechanisms",
        "phenomenon": "climate change",
        "early_researcher": "Arrhenius",
        "early_finding": "CO2 warming effect",
        "recent_focus": "renewable energy",
        "recent_researcher": "Mann",
        "recent_finding": "hockey stick graph",
        "gap1": "regional climate models",
        "gap2": "impact on biodiversity",
        "gap3": "long-term projections",
        "research_design": "longitudinal study",
        "design_justification": "captures changes over time",
        "sample_size": "1000 participants",
        "sampling_method": "random sampling",
        "inclusion_criteria": "residents of affected areas",
        "exclusion_criteria": "non-residents",
        "data_collection_method1": "surveys",
        "data_collection_method2": "interviews",
        "data_collection_method3": "satellite data",
        "analysis_method1": "regression analysis",
        "analysis_method2": "thematic analysis",
        "statistical_test": "ANOVA",
        "hypothesis": "emissions affect temperature",
        "ethical_concern1": "participant privacy",
        "ethical_concern2": "data security",
        "ethical_measure1": "anonymized data",
        "ethical_measure2": "secure storage",
        "expected_finding1": "emissions correlate with warming",
        "expected_finding2": "policy changes reduce impact",
        "theoretical_implication": "supports greenhouse theory",
        "practical_implication": "guides policy decisions",
        "policy_implication": "informs international agreements",
        "phase1_activities": "literature review",
        "phase2_activities": "data collection",
        "phase3_activities": "data analysis",
        "phase4_activities": "report writing",
        "resource1": "research assistants",
        "resource2": "computing resources",
        "resource3": "field equipment",
        "budget_amount": "$50,000",
        "budget_item1": "salaries",
        "budget_item2": "equipment"
    }
} 