ARG VERSION="0.4.23"
FROM ghcr.io/agentgateway/agentgateway:${VERSION} as source

FROM ghcr.io/astral-sh/uv:0.6.5-debian-slim AS final

COPY --from=source /app/agentgateway /bin/agentgateway

ARG TARGETARCH

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    ca-certificates \
    curl \
    gnupg \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN uv python install 3.12

EXPOSE 3000
EXPOSE 19000

WORKDIR /app
ENTRYPOINT ["/bin/agentgateway"]


